services:
    app.item_repository:
        class: AppBundle\Infrastructure\ItemRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['AppBundle:Item']

    app.item_manager:
        class: AppBundle\Item\ItemManager
        arguments: ['@app.item_repository']

    app.flush_subscriber:
        class: AppBundle\Infrastructure\FlushSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - {name:'kernel.event_listener', event: 'kernel.response', method: 'onKernelResponse'}
